from time import sleep
from userbot import CMD_HELP
from userbot.events import register


@register(outgoing=True, pattern='^.mantan(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    sleep(1)
    await typew.edit("`HAI MANTAN 🙂`")
    sleep(1)
    await typew.edit("`BERUBAH KARENA DIA`")
    sleep(1)
    await typew.edit("`ALASAN BANYAK`")
    sleep(1)
    await typew.edit("`SOK SIBUK`")
    sleep(1)
    await typew.edit("`JAWAB SINGKAT AMAT PAS BELUM PUTUS`")
    sleep(1)
    await typew.edit("`KAU PERGI DENGANNYA`")
    sleep(1)
    await typew.edit("`SUNGGUH TEGA`")
    sleep(1)
    await typew.edit("`AKU LIAT KAU BERDUAAN 🙃`")
    sleep(1)
    await typew.edit("`KAN KEINGET LAGI MASA SAKITNYA `")
    sleep(1)
    await typew.edit("`CUMA MANTAN AJAPUN 😂`")
    sleep(3)
    await typew.edit("`😁`")
    sleep(2)
    await typew.edit("`MANTAN KEKASIH GELAP`")
    sleep(2)
    await typew.edit("`😂`")
# Create by myself @localheart


@register(outgoing=True, pattern='^.sedih(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    sleep(1)
    await typew.edit("`AKU SEDIH LOH `")
    sleep(1)
    await typew.edit("`KAU SEDIH GAK?`")
    sleep(1)
    await typew.edit("`🥺🥺🥺`")
    sleep(1)
    await typew.edit("`🥺🥺`")
    sleep(1)
    await typew.edit("`😭🙃`")
    sleep(1)
    await typew.edit("`😭😭😭😭`")
    sleep(1)
    await typew.edit("`SUNGGUH TEGA`")
    sleep(1)
    await typew.edit("`AKU LIAT KAU BERDUAAN😭`")
    sleep(1)
    await typew.edit("`🙂🙃😭`")
    sleep(1)
    await typew.edit("`🥺😭🥺😭🥺😭🥺`")
# Create by myself @localheart


@register(outgoing=True, pattern='^.salam(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    sleep(1)
    await typew.edit("`Bismillah semoga diterima salamnya`")
    sleep(1)
    await typew.edit("`Assalammuallaikum😊😊`")
# Create by myself @localheart


@register(outgoing=True, pattern='^.jawab(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    sleep(1)
    await typew.edit("`Eh lupa jawab salam maaf atuh`")
    sleep(1)
    await typew.edit("`Walaikumsalam😊`")
# Create by myself @localheart


@register(outgoing=True, pattern="^.pantun$")
async def koc(e):
    if not e.text[0].isalpha() and e.text[0] not in ("/", "#", "@", "!"):
        sleep(1)
        await e.edit("I LOVEE YOUUU 💕")
        sleep(2)
        await e.edit("IKAN HIU")
        sleep(2)
        await e.edit("MAKAN ULAR")
        sleep(2)
        await e.edit("EH SALAH APA YA LUPA TADI")
        sleep(2)
        await e.edit("EH GOBLOK")
        sleep(2)
        await e.edit("LU GOBLOK")
        sleep(1)
        await e.edit("BUAT PARA CEWEK ILOVE U😍")
        sleep(2)
        await e.edit("JANGAN PERNAH BILANG ADA YANG MENYAKITIMU")
        sleep(2)
        await e.edit("NANTI ORANG ITU AKAN HILANG")
        sleep(2)
        await e.edit("MAU GA JADI PACARKU")
        sleep(1)
        await e.edit("TETAP DISINI")
        sleep(2)
        await e.edit("TENAMANI AKU")
        sleep(1)
        await e.edit("SEPANJANG HIDUPKUUU")
        sleep(2)
        await e.edit("PERCAYALAH KUAKAN SELINGKUH 💕")
        sleep(1)
        await e.edit("MENDUAKANMU")
        sleep(2)
        await e.edit("SAYANG")
        sleep(1)
        await e.edit("KAMU")
        sleep(1)
        await e.edit("SAYANG")
        sleep(1)
        await e.edit("YOK GASKANNNN")
        sleep(2)
        await e.edit("I LOVE YOUUUU")
        sleep(1)
        await e.edit("MY BABY")
        sleep(1)
        await e.edit("💕💞💘💝")
        sleep(1)
        await e.edit("💘💕💞💝")
        sleep(1)
        await e.edit("MUACH MUACH😍😁💞")
# Create by myself @localheart


@register(outgoing=True, pattern='^.galau(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    sleep(5)
    await typew.edit("`🎸 JRENG JRENG JRENG `")
    sleep(3)
    await typew.edit("`KUMOHON KAU MENGERTI COBALAH KAU TAMBAHKAN HATI`")
    sleep(2)
    await typew.edit("`🎸 MUNGKIN DISAAT INI CINTA KITA SEDANG DIUJI `")
    sleep(2)
    await typew.edit("`TABAHKANLAH HATIMU OLEH SIKSA ORANG TUAMU `")
    sleep(2)
    await typew.edit("`🎸 KUYAKIN KITA MAMPU BILA KITA SALING MENUNGGU `")
    sleep(2)
    await typew.edit("`KU KAN SELALU SENANG MENUNGGU (WALAU HANYA KEKASIH GELAP MU`")
    sleep(2)
    await typew.edit("`🎸 SAD YA SEBAGAI SIMPANAN `")
    sleep(2)
    await typew.edit("`DAHLA MALES 🙂`")
# Create by myself @localheart


@register(outgoing=True, pattern='^.sad(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    sleep(1)
    await typew.edit("` MARI KITA NANGIS-NANGIS BUAT YANG LAGI PATAH HATI/BROKENHOME `")
    sleep(2)
    await typew.edit("`1`")
    sleep(2)
    await typew.edit("` 2 `")
    sleep(2)
    await typew.edit("` 3 `")
    sleep(2)
    await typew.edit("` 🥺 `")
    sleep(2)
    await typew.edit("`😭`")
    sleep(2)
    await typew.edit("`🥺`")
    sleep(2)
    await typew.edit("`😭`")
# Create by myself @localheart


@register(outgoing=True, pattern='^razia(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    sleep(1)
    await typew.edit("` 🏍️ `")
    sleep(1)
    await typew.edit("`ADA POLISI`")
    sleep(1)
    await typew.edit("` 🚓 `")
    sleep(1)
    await typew.edit("` WIU WIU`")
    sleep(1)
    await typew.edit("` 🚓 `")
    sleep(2)
    await typew.edit("`🚑`")
    sleep(1)
    await typew.edit("`🚓`")
    sleep(1)
    await typew.edit("`🚥 Yah Ketangkap`")
# Create by myself @localheart


@register(outgoing=True, pattern='^/wkwk(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    sleep(1)
    await typew.edit("` 😂 `")
    sleep(1)
    await typew.edit("`🤣`")
    sleep(1)
    await typew.edit("` 😁 `")
    sleep(1)
    await typew.edit("` 😅`")
    sleep(1)
    await typew.edit("`😄`")
    sleep(2)
    await typew.edit("`😀`")
    sleep(1)
    await typew.edit("`😆`")
    sleep(1)
    await typew.edit("`😓`")
# Create by myself @localheart


@register(outgoing=True, pattern='^melamar(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    sleep(1)
    await typew.edit("` AKU ADALAH KAMU  `")
    sleep(1)
    await typew.edit("`AKU INGIN MENJADI TEMAN HIDUP UNTUKMU`")
    sleep(2)
    await typew.edit("` MAU GAK KALAU GAK MAU AKU TARIK LAGI KATA NYA `")
    sleep(2)
    await typew.edit("`KALAU MAU MAH TROBOS AJA`")
    sleep(3)
    await typew.edit("`😄`")
    sleep(2)
    await typew.edit("`BISMILAH`")
    sleep(3)
    await typew.edit("`KUCINTAI DIRIMU SEKARANG DENGAN SAH`")
    sleep(1)
    await typew.edit("`DILAN 1990`")
# Create by myself @localheart


@register(outgoing=True, pattern='^buaya(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    sleep(1)
    await typew.edit("`KAMU MAU LIHAT BUAYA `")
    sleep(1)
    await typew.edit("`INISIAL R 🐊`")
    sleep(1)
    await typew.edit("` INISIAL V 🦎 `")
    sleep(1)
    await typew.edit("`INISIAL I 👌`")
    sleep(1)
    await typew.edit("`INISIAL D 🐊🦎`")
    sleep(2)
    await typew.edit("`C 🐊 DARAT`")
    sleep(1)
    await typew.edit("`U🦎 LAUT`")
    sleep(1)
    await typew.edit("`ITULAH BUAYA BUAYA HATI HATI YA 😁`")
# Create by myself @localheart


@register(outgoing=True, pattern='^.yang(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    sleep(1)
    await typew.edit("` Sayang udah makan? `")
    sleep(1)
    await typew.edit("`Apa Kabar mu`")
    sleep(1)
    await typew.edit("` Kuharap  `")
    sleep(1)
    await typew.edit("` kau`")
    sleep(1)
    await typew.edit("`Baik-baik saja`")
    sleep(2)
    await typew.edit("`Aku sayang kamu`")
    sleep(1)
    await typew.edit("`Tapi kamu nya tidak`")
    sleep(1)
    await typew.edit("`Semoga engkau baik baik saja meski tak kumiliki.`")
# Create by myself @localheart


@register(outgoing=True, pattern='^.raziamasker(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit("`ADA SATPOL PP LARI.....`")
    sleep(1)
    await typew.edit("`WOI SATPOL PP MASKER KALIAN !!`")
    sleep(1)
    await typew.edit("`🏃                        🚓`")
    await typew.edit("`🏃                       🚓`")
    await typew.edit("`🏃                      🚓`")
    await typew.edit("`🏃                     🚓`")
    await typew.edit("`🏃   `LARII`          🚓`")
    await typew.edit("`🏃                   🚓`")
    await typew.edit("`🏃                  🚓`")
    await typew.edit("`🏃                 🚓`")
    await typew.edit("`🏃                🚓`")
    await typew.edit("`🏃               🚓`")
    await typew.edit("`🏃              🚓`")
    await typew.edit("`🏃             🚓`")
    await typew.edit("`🏃            🚓`")
    await typew.edit("`🏃           🚓`")
    await typew.edit("`🏃LUMAYAN CAPEK😪   🚓`")
    await typew.edit("`🏃  LANJUT LARI         🚓`")
    await typew.edit("`🏃            🚓`")
    await typew.edit("`🏃             🚓`")
    await typew.edit("`🏃              🚓`")
    await typew.edit("`🏃               🚓`")
    await typew.edit("`🏃     SALTO DULU          🚓`")
    await typew.edit("`🏃                 🚓`")
    await typew.edit("`🏃                  🚓`")
    await typew.edit("`🏃                   🚓`")
    await typew.edit("`🏃                    🚓`")
    await typew.edit("`🏃                     🚓`")
    await typew.edit("`🏃  Huh-Huh           🚓`")
    await typew.edit("`🏃                   🚓`")
    await typew.edit("`🏃                  🚓`")
    await typew.edit("`🏃                 🚓`")
    await typew.edit("`🏃                🚓`")
    await typew.edit("`🏃               🚓`")
    await typew.edit("`🏃              🚓`")
    await typew.edit("`🏃             🚓`")
    await typew.edit("`🏃            🚓`")
    await typew.edit("`🏃           🚓`")
    await typew.edit("`🏃          🚓`")
    await typew.edit("`🏃         🚓`")
    await typew.edit("`CAPE BANGET !!!`")
    sleep(1)
    await typew.edit("`🏃       🚓`")
    await typew.edit("`🏃      🚓`")
    await typew.edit("`🏃     🚓`")
    await typew.edit("`🏃    🚓`")
    await typew.edit("`Dahlah Pasrah Aja`")
    sleep(1)
    await typew.edit("`🧎🚓🚓 KETANGKAP KAUKAN MANA MASKERNYA`")
    sleep(2)
    await typew.edit("`🤦TINGGAL DIRUMAH PAK`")
# Create by myself @localheart


@register(outgoing=True, pattern="^.ngabuburit$")
async def koc(e):
    if not e.text[0].isalpha() and e.text[0] not in ("/", "#", "@", "!"):
        await e.edit("BOSEN GAK ADA KEGIATAN")
        sleep(1)
        await e.edit("DIRUMAH MULU")
        sleep(1)
        await e.edit("SEKOLAH DILIBURKAN")
        sleep(1)
        await e.edit("TEMEN GADA")
        sleep(1)
        await e.edit("`MENDING JALAN JALAN`")
        sleep(1)
        await e.edit("SAMBIL NGABUBURIT SEMOGA GADA RAZIA YA:)")
        sleep(1)
        await e.edit("...........................🚐")
        await e.edit("..........................🚐.")
        await e.edit("..............🛺.........🚐..")
        await e.edit("..............🛺........🚐...")
        await e.edit("..............🛺.......🚐....")
        await e.edit("..............🛺......🚐.....")
        await e.edit("..............🛺.....🚐......")
        await e.edit("..............🛺....🚐.......")
        await e.edit("..............🛺...🚐........")
        await e.edit("..............🛺.🚐..........")
        await e.edit("..............🛺🚐...........")
        await e.edit("............🚐🛺.............")
        await e.edit("..........🚐...🛺............")
        await e.edit(".........🚐.....🛺...........")
        await e.edit("........🚐.......🛺..........")
        await e.edit(".......🚐..........🛺........")
        await e.edit("......🚐.............🛺......")
        await e.edit(".....🚐...............🛺.....")
        await e.edit("....🚐..................🛺...")
        await e.edit("..🚐.....................🛺..")
        await e.edit(".🚐........................🛺")
        await e.edit("🚐...........................")
        await e.edit("...........................🚐")
        await e.edit("........🏠🏡🏘️............🚐.")
        await e.edit("........🏘️🏡🏠...........🚐..")
        await e.edit("........🏘️🏡🏠..........🚐...")
        await e.edit("........🏘️🏡🏠.........🚐....")
        await e.edit("........🏘️🏘️🏘️........🚐.....")
        await e.edit("........🏡🏠🏡.......🚐......")
        await e.edit("........🏘️🏡🏠......🚐.......")
        await e.edit("........🏘️🏡🏠.....🚐........")
        await e.edit("........🏘️🏡🏠....🚐.........")
        await e.edit("........🏘️🏡🏠...🚐..........")
        await e.edit("........🏘️🏡🏠..🚐...........")
        await e.edit("........🏘️🏡🏠.🚐............")
        await e.edit("........🏘️🏡🏠🚐.............")
        await e.edit("........🏘️🏡🚐🏠.............")
        await e.edit("........🏘️🚐🏡🏠.............")
        await e.edit("........🚐🏠🏡🏘️.............")
        await e.edit(".......🚐.🏠🏡🏡.............")
        await e.edit("......🚐..🏘️🏡🏠.............")
        await e.edit(".....🚐...🏘️🏡🏠.............")
        await e.edit("....🚐....🏘️🏠🏡.............")
        await e.edit("...🚐.....🏠🏡🏘️.............")
        await e.edit("..🚐......🏘️🏡🏠.............")
        await e.edit(".🚐.......🏘️🏡🏠.............")
        await e.edit("🚐........🏠🏡🏘️.............")
        await e.edit("...........................🚐")
        await e.edit("............🕌............🚐.")
        await e.edit("............🕌...........🚐..")
        await e.edit("............🕌..........🚐...")
        await e.edit("............🕌.........🚐....")
        await e.edit("............🕌........🚐.....")
        await e.edit("............🕌.......🚐......")
        await e.edit("............🕌......🚐.......")
        await e.edit("............🕌.....🚐........")
        await e.edit("............🕌....🚐.........")
        await e.edit("............🕌...🚐..........")
        await e.edit("............🕌..🚐...........")
        await e.edit("............🕌.🚐............")
        await e.edit("............🕌🚐.............")
        await e.edit("............🚐🕌.............")
        await e.edit("...........🚐.🕌.............")
        await e.edit("..........🚐..🕌.............")
        await e.edit(".........🚐...🕌.............")
        await e.edit("........🚐....🕌ᴬᴸᴸᴬᴴᵁ ᴬᴷᴮᴬᴿ²ˣ.")
        await e.edit("ᵂᴬᴴ ᴬᴰᶻᴬᴺ🚐....🕌.............")
        await e.edit("ˢᴴᴼᴸᴬᵀ ᴬᴴ🚐....🕌.............")
        await e.edit(".........🚐...🕌............")
        await e.edit("...........🚐.🕌............")
        await e.edit("............🚐🕌............")
        sleep(1)
        await e.edit("CERITANYA LAGI SHOLAT")
        sleep(1)
        await e.edit("KARNA SI DARA MAU MENAMBAH PAHALA")
        sleep(1)
        await e.edit("DIA PUN SHALAT")
        sleep(1)
        await e.edit("KATA SI DARA")
        sleep(1)
        await e.edit("SHOLAT LAH SEBELUM KAU DI SHOLATKAN")
        sleep(1)
        await e.edit("Lagi shalat🚐🕌.............")
        await e.edit("Lagi shalat..........🚐.🕌.............")
        await e.edit("...............🚐..🕌.............")
        await e.edit("..............🚐...🕌.............")
        await e.edit(".............🚐....🕌.............")
        await e.edit("............🚐.....🕌.............")
        await e.edit("...........🚐......🕌.............")
        await e.edit("..........🚐.......🕌.............")
        await e.edit("🏘️.......🚐........🕌.............")
        await e.edit("🏘️......🚐.........🕌.............")
        await e.edit("🏘️.....🚐..........🕌.............")
        await e.edit("🏘️....🚐...........🕌.............")
        await e.edit("🏘️...🚐............🕌.............")
        await e.edit("🏘️..🚐.............🕌.............")
        await e.edit("🏘️.🚐..............🕌.............")
        await e.edit("🏘️🚐...............🕌.............")
        await e.edit("..............................🚐🏘️")
        await e.edit(".............................🚐.🏘️")
        sleep(1)
        await e.edit("...........DIPERJALANAN ADA JUALAN ES CENDOL................🚐..🏘️")
        sleep(1)
        await e.edit(".............BELI ES CENDOL AH ..............🚐...🏘️")
        sleep(1)
        await e.edit("..........................🚐....🏘️")
        await e.edit(".........................🚐.....🏘️")
        await e.edit("........................🚐......🏘️")
        await e.edit(".......................🚐.......🏘️")
        await e.edit(".....................🚐.........🏘️")
        await e.edit("....................🚐..........🏘️")
        await e.edit("...................🚐...........🏘️")
        await e.edit("..................🚐............🏘️")
        await e.edit(".................🚐.............🏘️")
        await e.edit("................🚐..............🏘️")
        await e.edit("...............🚐...............🏘️")
        await e.edit("..............🚐................🏘️")
        await e.edit(".............🚐.................🏘️")
        await e.edit("............🚐..................🏘️")
        await e.edit("...........🚐...................🏘️")
        await e.edit("..........🚐....................🏘️")
        await e.edit(".........🚐.....................🏘️")
        await e.edit("........🚐......................🏘️")
        await e.edit(".......🚐.......................🏘️")
        await e.edit("......🚐........................🏘️")
        await e.edit(".....🚐.........................🏘️")
        await e.edit("....🚐..........................🏘️")
        await e.edit("...🚐...........................🏘️")
        await e.edit("..🚐............................🏘️")
        await e.edit(".🚐.............................🏘️")
        await e.edit("🚐..............................🏘️")
        await e.edit("SEBELUM SAMPAI RUMAH EH MALAH KECELAKAAN")
# Create by myself @localheart

CMD_HELP.update({
    "alphakata-kata":
    "📚 **Cmd** : `.yang`\
    \n📄 **Descriptions** : apa kabarmu sayang.\
    \n\n📚 **Cmd** : `.sayang`\
    \n📄 **Descriptions** : untuk jadi buaya.\
    \n\n📚 **Cmd** : .`buaya`\
    \n📄 **Descriptions** : contoh inisial buaya.\
    \n\n📚 **Cmd** : .`melamar`\
    \n📄 **Descriptions** : kata kata dilan.\
    \n\n📚 **Cmd** : .`wkwk`\
    \n📄 **Descriptions** : Tertawa emot.\
    \n\n📚 **Cmd** : .`razia`\
    \n📄 **Descriptions** :bada razia😂.\
    \n\n📚 **Cmd** : `.sad`\
    \n📄 **Descriptions** : sedihnya oalah.\
    \n\n📚 **Cmd** : `.galau`\
    \n📄 **Descriptions** : galau lah situ.\
    \n\n📚 **Cmd** : `.mantan`\
    \n📄 **Descriptions** : teringat mantan.\
    \n\n📚 **Cmd** : `.raziamasker.`\
    \n📄 **Descriptions** : Razia masker.\
    \n\n📚 **Cmd** : `.ngabuburit`.\
    \n📄 **Descriptions** : Ngabuburit."
})
